import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      items: [
        "getting-started/installation",
        "getting-started/setting-up-models",
        "getting-started/quick-start",
        "getting-started/your-first-flow",
        "getting-started/project-structure",
      ],
    },
    {
      type: "category",
      label: "Core",
      items: [
        {
          type: "category",
          label: "Fundamentals",
          items: [
            "fundamentals/overview",
            "fundamentals/blocks",
            "configuration/blocks",
            "fundamentals/flows",
            "configuration/flow",
            "fundamentals/actions",
            "fundamentals/state-and-scopes",
            "fundamentals/state-operations",
            "fundamentals/capabilities",
            "fundamentals/type-system",
            "fundamentals/models",
            "configuration/environment",
            {
              type: "category",
              label: "Advanced",
              collapsed: true,
              items: [
                "advanced/capabilities-authoring",
                "advanced/generator-context",
                "advanced/generator-prompts-markdown",
                "advanced/custom-model-resolver",
                "advanced/block-state",
                "advanced/state-targets-and-parents",
                "state/mutation-model",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Composition",
          items: [
            "sequencers/overview",
            "sequencers/composing-blocks",
            "sequencers/control-flow",
            "sequencers/connectors",
            {
              type: "category",
              label: "Advanced",
              collapsed: true,
              items: [
                "sequencers/wait-for-condition",
                "advanced/sequencer-side-chains",
                "advanced/sequencer-state",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Resources",
          items: [
            "resources/overview",
            "resources/storage",
            "resources/collections",
            "resources/external-collections",
            "resources/reactive-blocks",
            "resources/edges",
            "resources/client-access",
            "resources/searching",
            "resources/manifest",
            {
              type: "category",
              label: "Advanced",
              collapsed: true,
              items: ["advanced/resource-templates-markdown"],
            },
          ],
        },
        {
          type: "category",
          label: "Streaming and Items",
          items: [
            "streaming/overview",
            "streaming/emitting-items",
            "streaming/items",
            {
              type: "category",
              label: "Advanced",
              collapsed: true,
              items: ["streaming/trace-channel"],
            },
          ],
        },
        {
          type: "category",
          label: "Engine",
          items: [
            "server/setup",
            "configuration/runtime",
            "advanced/manual-flow-execution",
            "persistence/overview",
            "server/background-work",
            "server/authentication",
            {
              type: "category",
              label: "Hosting",
              items: [
                "server/host-adapters",
                "server/mcp",
                "server/chat",
                "server/webhooks",
                {
                  type: "category",
                  label: "Scheduled actions",
                  items: ["server/scheduled", "server/schedule-index"],
                },
              ],
            },
            {
              type: "category",
              label: "Advanced",
              collapsed: true,
              items: [
                "server/connection-resilience",
                "advanced/error-handling",
                "advanced/error-capture",
                "advanced/concurrency-policies",
                "advanced/idempotency",
                "advanced/durable-execution",
                "advanced/block-memoization-and-replay",
                "advanced/generator-and-router-suspend-resume",
                "advanced/inbound-transports",
                "advanced/voice",
                "advanced/flow-isolation",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "fsdev",
          items: [
            "cli/overview",
            "cli/configuration",
            "cli/agent-dev-loop",
            "cli/interactive-chat",
            {
              type: "category",
              label: "DevTool",
              items: [
                "devtool/overview",
                "devtool/setup",
                "devtool/embedding",
                "devtool/observing-resource-loads",
                "devtool/debug-vs-client-state",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Client",
          items: [
            "client/overview",
            "client/react",
            "configuration/client",
          ],
        },
        {
          type: "category",
          label: "Testing",
          items: [
            "testing/overview",
            "testing/testing-flows",
            "testing/flow-integration-tests",
            "testing/end-to-end-tests",
            "testing/benchmarks",
          ],
        },
        "configuration/overview",
      ],
    },
    {
      type: "category",
      label: "Orchestration",
      items: [
        "orchestration/overview",
        "orchestration/task-substrate",
        "orchestration/task-board",
        "orchestration/configuration",
        "orchestration/agents",
        {
          type: "category",
          label: "Skills",
          items: [
            "skills/overview",
            "skills/binding",
            "skills/activation",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          collapsed: true,
          items: [
            "orchestration/goal-seek-loop",
            "orchestration/flow-policy",
            "orchestration/context-supply",
            "skills/authoring",
            "skills/delegation",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Ecosystem",
      items: [
        "ecosystem/overview",
        {
          type: "category",
          label: "Patterns",
          items: [
            "patterns/overview",
            {
              type: "category",
              label: "Coordination Patterns",
              items: [
                "patterns/parallelTasks",
                "patterns/supervisor",
                "patterns/plan-and-execute",
                "patterns/routed-specialists",
                "patterns/round-robin",
                "patterns/debate",
                "patterns/event-actors",
              ],
            },
            {
              type: "category",
              label: "Other Patterns",
              items: ["patterns/response-auditor"],
            },
            {
              type: "category",
              label: "Utility Blocks",
              items: [
                "patterns/utility-blocks/core",
                "patterns/utility-blocks/extensions",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Tools",
          items: [
            "tools/overview",
            "tools/search",
            "tools/fetch",
            "tools/crawl",
            "tools/bash",
            "tools/mcp",
            "tools/claude-code-cli",
            "tools/claude-code-sdk",
          ],
        },
        {
          type: "category",
          label: "UI",
          items: [
            "ui/overview",
            "ui/common-components",
            "ui/flow-aware-components",
            "ui/generative",
          ],
        },
        {
          type: "category",
          label: "Memory",
          items: [
            "memory/overview",
            "memory/configuration",
            "memory/relations",
            "memory/recall-tool",
            "memory/hygiene",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: [
        "api/core",
        "api/server",
        "api/client",
        "api/react",
        "api/testing",
        "api/benchmarks",
        "api/cli",
      ],
    },
  ],
};

export default sidebars;
