// Generated by `fsdev gen`. Do not edit.
//
// One entry per file under `flows/workers/`, `flows/channels/` and `blocks/`,
// one per TypeScript file in a `resources/` folder, one per seat per file in
// a team's or a worker's own `blocks/` folder, and one per file in a
// package's `blocks/` folder.
// Add or rename a file and re-run `fsdev gen`; `fsdev gen --check` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.

import type { BlockDefinition } from "@flow-state-dev/core";
import packageblock_teams__support__workers__iris__packages__ticket_desk__stamp_ticket from "./teams/support/workers/iris/packages/ticket-desk/blocks/stamp-ticket";
import packageblock_teams__support__workers__tess__packages__ticket_desk__stamp_ticket from "./teams/support/workers/tess/packages/ticket-desk/blocks/stamp-ticket";

export const kinds = {};

export const channelKinds = {};

export const blocks = {};

export const resourceModules = {};

export const seatBlocks = {};

export const packageBlocks = {
  "teams/support/workers/iris/packages/ticket-desk": {
    "stamp-ticket": packageblock_teams__support__workers__iris__packages__ticket_desk__stamp_ticket,
  },
  "teams/support/workers/tess/packages/ticket-desk": {
    "stamp-ticket": packageblock_teams__support__workers__tess__packages__ticket_desk__stamp_ticket,
  },
} satisfies Record<string, Record<string, BlockDefinition>>;
