// Generated by `fsdev gen`. Do not edit.
//
// One entry per file under `flows/workers/`, `flows/channels/` and `blocks/`,
// one per TypeScript file in a `resources/` folder, one per seat per file in
// a team's or a worker's own `blocks/` folder, and one per file in a
// package's `blocks/` folder.
// Add or rename a file and re-run `fsdev gen`; `fsdev gen --check` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.

import type { ChannelInstancesOptions } from "@flow-state-dev/workforce";
import channel_digest from "./flows/channels/digest";

export const kinds = {};

export const channelKinds = {
  "digest": channel_digest,
} satisfies NonNullable<ChannelInstancesOptions["kinds"]>;

export const blocks = {};

export const resourceModules = {};

export const seatBlocks = {};

export const packageBlocks = {};
