/**
 * Empty schema-valid payloads tagged `source: "unavailable"`.
 *
 * Returned by tools in live mode when no provider can answer (either because
 * none is wired or because every wired provider failed). The analyst sees
 * `null` for every figure the desk did not observe, empty arrays for the
 * collections, and the transcript pill marks the result as unavailable — honest
 * about coverage, no false fixture data masquerading as live data.
 *
 * NULL, NOT ZERO (FIX-1063). A builder here fires precisely when nothing was
 * measured, so every numeric field it emits is unobserved by construction.
 * Writing `0` made a missing market cap arithmetically indistinguishable from a
 * company worth nothing, and a missing 200-day average indistinguishable from a
 * flat trend. A genuinely measured `0` still reads `0` — that value comes from a
 * provider path, never from this file.
 */
import type { DiscoveryTool, ToolInput, ToolName, ToolOutput } from "./schemas";

type EmptyBuilder<T extends ToolName> = (input: ToolInput<T>) => ToolOutput<T>;

const builders: { [K in ToolName]: EmptyBuilder<K> } = {
  get_balance_sheet: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    totalAssets: null,
    totalLiabilities: null,
    totalEquity: null,
    cashAndEquivalents: null,
    totalDebt: null,
    unit: "USD billions",
  }),
  get_income_statement: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    revenue: null,
    grossProfit: null,
    operatingIncome: null,
    netIncome: null,
    yoyRevenueGrowth: null,
    unit: "USD billions",
  }),
  get_cashflow: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    operating: null,
    investing: null,
    financing: null,
    freeCashFlow: null,
    unit: "USD billions",
  }),
  get_fundamentals: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    marketCap: null,
    forwardPE: null,
    trailingPE: null,
    priceToSales: null,
    returnOnEquity: null,
    operatingMargin: null,
    grossMargin: null,
    dividendYield: null,
  }),
  get_price_history: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    range: i.range ?? "1mo",
    bars: [],
  }),
  compute_indicators: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    rsi14: null,
    macd: { line: null, signal: null, histogram: null },
    atr14: null,
    trend: null,
    sma50: null,
    sma200: null,
    bollinger: { upper: null, middle: null, lower: null },
    vwma20: null,
    stoch: { k: null, d: null },
    kdj: { k: null, d: null, j: null },
    obv: null,
  }),
  search_news: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    items: [],
  }),
  get_market_news: (i) => ({
    source: "unavailable",
    asOf: i.date,
    items: [],
  }),
  get_macro_news: (i) => ({
    source: "unavailable",
    asOf: i.date,
    items: [],
  }),
  get_macro_indicators: (i) => ({
    source: "unavailable",
    asOf: i.date,
    cpiYoy: null,
    unemployment: null,
    fedFundsRate: null,
    tenYearYield: null,
    oilWtiUsd: null,
    yieldCurve2s10s: null,
    hyCreditSpread: null,
    dollarIndex: null,
    industrialProduction: null,
  }),
  get_social_sentiment: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    score7d: null,
    positive: null,
    negative: null,
    neutral: null,
    shortInterestPct: null,
    posts: [],
  }),
  get_reddit_mentions: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    mentions7d: null,
    topThreads: [],
  }),
  get_prediction_markets: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    tickerMarkets: [],
    backdropMarkets: [],
    backdropTheme: "",
    coverageQuality: "absent",
  }),
  get_insider_transactions: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    transactions: [],
    windowDays: 90,
  }),
  get_company_profile: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    name: "",
    sector: null,
    industry: null,
    country: null,
    exchange: null,
    currency: null,
    businessDescription: null,
    marketCapUsd: null,
    employees: null,
    ipoDate: null,
    website: null,
    websiteMetaDescription: null,
    searchSnippets: null,
  }),
  discover_fundamentals_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  discover_sentiment_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  discover_technical_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  discover_profile_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  get_sector_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    sector: null,
    industry: null,
    sectorEtf: null,
    nameReturn1m: null,
    sectorEtfReturn1m: null,
    broadMarketReturn1m: null,
    relativeStrength1m: null,
    sectorVsMarket1m: null,
  }),
  get_sector_peers: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    grouping: null,
    peers: [],
    peerMedianReturn1m: null,
  }),
  get_cross_asset_flow: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    windowDays: 63,
    ratios: [],
    riskAppetite: null,
    riskAppetiteScore: null,
    nameReturn: null,
    broadMarketReturn: null,
    nameVsBroadMarket: null,
    liquidity: null,
  }),
  discover_market_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  discover_macro_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  get_factor_ranks: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    peerCount: null,
    factors: [],
    compositeFactorPercentile: null,
  }),
  get_risk_regime: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    betaMarket: null,
    betaSector: null,
    rSquared: null,
    realizedVolAnnualized: null,
    volRegime: null,
    volPercentile: null,
    correlationMarket: null,
    correlationRegime: null,
  }),
  get_quant_composites: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    altmanZ: null,
    altmanZone: null,
    altmanVariant: null,
    piotroskiF: null,
    piotroskiBreakdown: [],
    coverageNote: "Statement data unavailable.",
  }),
  get_short_interest: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    shortInterest: null,
    shortInterestPctFloat: null,
    daysToCover: null,
    settlementDate: null,
  }),
  get_institutional_ownership: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    reportDate: null,
    holderCount: null,
    totalSharesHeld: null,
    netShareChange: null,
    flowDirection: null,
    topHolders: [],
  }),
  get_options_chain: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    spotPrice: null,
    nearestExpiry: null,
    atmIv: null,
    ivTermStructure: null,
    ivTermSlope: null,
    skew25Delta: null,
    putCallOiRatio: null,
    totalOpenInterest: null,
    totalVolume: null,
    expiriesCovered: 0,
  }),
  get_futures_curve: (i) => ({
    source: "unavailable",
    asOf: i.date,
    products: [],
    riskTone: null,
  }),
  discover_quant_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
  get_sec_filings: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    recentFilings: [],
    registrationFilings: [],
    materialEvents: [],
    latestPeriodic: null,
    redFlagProbes: [],
  }),
  get_analyst_estimates: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    ratingsDistribution: null,
    earningsSurprises: [],
    consensusEstimates: null,
    priceTargets: null,
    recentRatingActions: [],
  }),
  get_earnings_transcript: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    available: false,
    callDate: null,
    quarter: null,
    content: null,
  }),
  discover_disclosure_context: (i) => ({
    source: "unavailable",
    ticker: i.ticker,
    asOf: i.date,
    query: "",
    items: [],
    entityCheck: "unchecked",
    excluded: [],
  }),
};

export function emptyPayload<T extends ToolName>(tool: T, input: ToolInput<T>): ToolOutput<T> {
  return (builders[tool] as EmptyBuilder<T>)(input);
}

/**
 * Discovery-only cost-gated form: an empty discovery payload tagged
 * `source: "skipped"` rather than `"unavailable"`. Used by the four
 * `discover_*_context` tools when `costPreset !== "full"` to communicate to
 * downstream analysts that investigation was deliberately not run on this
 * preset, distinct from "tried and failed".
 */
export function skippedDiscoveryPayload<T extends DiscoveryTool>(
  tool: T,
  input: ToolInput<T>,
): ToolOutput<T> {
  return { ...emptyPayload(tool, input), source: "skipped" } as ToolOutput<T>;
}
