// The audit's findings, one entry per hit line (or `n` identical lines).
// `has` is a substring unique to the line within its file.
//   F   wording-only, fixed by FIX-1575
//   R1  moves with the follow-up rename of TaskDispatchInput's `seat` field
//   R2  moves with the follow-up on the pinned discovery domains
//   KC  keep: names Workforce/Orchestration as a consumer, the right direction
//   KE  keep: ordinary English, or a generic mechanism's own word
//   KP  keep: a title or anchor of a page or heading this issue does not own
const A = "docs/architecture/";
const CORE = "packages/core/src/";
const ENG = "packages/engine/src/";

export const LEDGER = [
  // docs/architecture
  { file: A + "action-forms.md", has: "reached by a task-board seat", c: "F" },
  { file: A + "action-forms.md", has: "dispatcher is a seat on a task board", c: "F" },
  { file: A + "authentication.md", has: "A hired instance is registered", c: "F" },
  // Added by the implementation (PLAN V2): reworded lines that name Workforce as a consumer.
  { file: A + "authentication.md", has: "Workforce pins every instance it hires this way", c: "KC" },
  { file: A + "capabilities.md", has: "seat advertising a tool", c: "F" },
  { file: A + "capabilities.md", has: "A worker-colocated tool is not an exemption", c: "F" },
  { file: A + "capabilities.md", has: "lets a block sit in one seat's own", c: "F" },
  { file: A + "capabilities.md", has: "for that seat — it does not grant", c: "F" },
  { file: A + "capabilities.md", has: "and the hire step resolves", c: "F" },
  { file: A + "capabilities.md", has: "builds the seat's declaration", c: "F" },
  { file: A + "capabilities.md", has: "Nothing crosses the fence that the seat", c: "F" },
  { file: A + "capabilities.md", has: "registration is a `workforce` concern", c: "F" },
  { file: A + "capabilities.md", has: "(Workforce does,", c: "KC" },
  { file: A + "dispatched-work.md", has: "board whose seat holds", c: "F" },
  { file: A + "dispatched-work.md", has: "seat* — the task-board surface", c: "KP" },
  { file: A + "dispatched-work.md", has: "a task seat sends the", c: "F" },
  { file: A + "dispatched-work.md", has: "`{ boardId, seat, taskId", c: "R1" },
  { file: A + "dispatched-work.md", has: "| the seat, one child per claiming session", c: "F" },
  { file: A + "dispatched-work.md", has: "so two seats that return", c: "F" },
  { file: A + "dispatched-work.md", has: "or `key` seat hands off to", c: "F" },
  { file: A + "dispatched-work.md", has: "installs at each dispatcher seat", c: "F" },
  { file: A + "dispatched-work.md", has: "seat. Any miss throws", c: "F" },
  { file: A + "dispatched-work.md", has: "the board's dispatcher seats, plus", c: "F" },
  { file: A + "dispatched-work.md", has: "boards with a dispatcher seat", c: "F" },
  { file: A + "dispatched-work.md", has: "against the seats that hand off", c: "F" },
  { file: A + "dispatched-work.md", has: "dispatcher seat needs park-exit", c: "F" },
  { file: A + "dispatched-work.md", has: "The hand-off at a dispatcher seat", c: "F" },
  { file: A + "dispatched-work.md", has: "Reading a board's seats", c: "F" },
  { file: A + "inbound-transports.md", has: "hand-off at a dispatcher seat", c: "F" },
  { file: A + "overview.md", has: "a task board seat holding", c: "F" },
  { file: A + "resources-and-client-data.md", has: "Workforce's private roster collection is the first consumer", c: "KC" },
  { file: A + "state-and-scopes.md", has: "Workforce's hired seat is the instance that uses it", c: "KC" },
  { file: A + "state-and-scopes.md", has: "Upgrading: moving hired seats' stored data", c: "KP" },
  { file: A + "state-and-scopes.md", has: "the key a task seat's `session` policy composed", c: "F" },
  // contributing, READMEs
  { file: "docs/contributing/architecture-reference.md", has: "A `task` dispatcher is a seat on a task board", c: "F" },
  { file: "docs/contributing/architecture-reference.md", has: "Default workforce agent kind:", c: "KC" },
  { file: "docs/contributing/architecture-reference.md", has: "Workforce admission rule — one gate", c: "KC" },
  { file: "docs/contributing/architecture-reference.md", has: "[Default Workforce Worker Kind]", c: "KP" },
  { file: "docs/contributing/best-practices/resources.md", has: "on a hired seat (an instance registered", c: "F" },
  { file: "packages/contracts/README.md", has: "`orchestration` and `workforce` each project", c: "KC" },
  { file: "packages/core/README.md", has: "from a `dispatcher({ action, session })` seat", c: "F" },
  { file: "packages/core/README.md", has: "is a seat on a task board", c: "F" },
  { file: "packages/core/README.md", has: "A task-board seat stamps", c: "F" },
  { file: "packages/core/README.md", has: "(one child per seat)", c: "F" },
  { file: "packages/core/README.md", has: "`{ boardId, seat, taskId", c: "R1" },
  { file: "packages/core/README.md", has: "[seat hired at runtime]", c: "F" },
  { file: "packages/core/README.md", has: "[owner-pinned instance](https://flow-state.dev/docs/workforce/durable-hire)", c: "KC" },
  { file: "packages/core/README.md", has: "seats, channels and skills are registered", c: "R2" },
  { file: "packages/engine/README.md", has: "Workforce pins each hired seat", c: "KC" },
  { file: "packages/scheduled/README.md", has: "On a hired seat (an instance", c: "F" },
  { file: "packages/scheduled/README.md", has: "the seat is registered to), the dispatch", c: "F" },
  { file: "packages/scheduled/README.md", has: "seat's storage for that organization", c: "F" },
  // contracts
  { file: "packages/contracts/src/types/manifest.ts", has: "Seats, channels, skills and resources already", c: "R2" },
  { file: "packages/contracts/src/types/manifest.ts", has: "(`core`, `orchestration`, `workforce`)", c: "KC" },
  { file: "packages/contracts/src/types/manifest.ts", has: "seat's own file, so renaming one", c: "R2" },
  { file: "packages/contracts/src/types/manifest.ts", has: "another seat can do belongs", c: "R2" },
  { file: "packages/contracts/src/types/manifest.ts", has: 'MANIFEST_DOMAINS = ["seats"', c: "R2" },
  { file: "packages/contracts/src/types/manifest.ts", has: '— `"seat"`, `"resource"`', c: "R2" },
  { file: "packages/contracts/src/types/manifest.ts", has: '`"createWorkforceCapability"`', c: "KC" },
  // core
  { file: CORE + "blocks/dispatcher.ts", has: "of its seats hand off without running", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "is a **seat on a task board**", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "A task-board seat is", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "a board seat that hands its rows off", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "session is already a task seat", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "this seat hands off to. Omit", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "the task board that holds the seat", c: "F" },
  { file: CORE + "blocks/dispatcher.ts", has: "* seat. Everything else", c: "F" },
  { file: CORE + "capability/types.ts", has: "the skills loader a seat switched on", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "DROPS a key nobody declared, so a roster", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "hand-off it holds at the seat", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "Entries some seat hands off to", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "A `per-task` seat lands every row", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "each row this seat hands off", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "A task dispatcher is a seat:", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "session })\\` seat to a board", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "the seat to a hand-off block", c: "F" },
  { file: CORE + "flow/defineFlow.ts", has: "the task entry the seat addresses, and task", c: "F" },
  { file: CORE + "helpers/block-graph.ts", has: "its dispatcher seats went", c: "F" },
  { file: CORE + "helpers/block-graph.ts", has: "the task entry its seat addresses", c: "F" },
  { file: CORE + "manifest/discovery-tools.ts", has: "`listSeats` / `listChannels`", c: "R2" },
  { file: CORE + "manifest/discovery-tools.ts", has: "the seats you can hand work to", c: "R2" },
  { file: CORE + "manifest/registry.ts", has: "a workforce with no", c: "F" },
  { file: CORE + "types/agent.ts", has: "a seat with `agent-ref`", c: "F" },
  { file: CORE + "types/block.ts", has: "of its seats hand off without running", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "which of its seats hand off. A substrate", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "one child per seat, shared by every row", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "shared across seats.", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "carries the seat's session policy", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "so the roster shows", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "statically which seats hand off and where", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "`seat` says which of the board's seats", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "The board seat the row is assigned to", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "seat: z.string().min(1)", c: "R1" },
  { file: CORE + "types/dispatch.ts", has: "framed(envelope.seat)", c: "R1" },
  { file: CORE + "types/dispatch.ts", has: "`dispatcher({ type: \"task\" })` seat on a board", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "seat: which board it is", c: "F" },
  { file: CORE + "types/dispatch.ts", has: "`dispatcher({ type: \"task\" })` seat, after", c: "F" },
  { file: CORE + "types/flow.ts", has: "seat on a board the", c: "F" },
  { file: CORE + "types/skill.ts", has: "the board's **tool seats**", c: "F" },
  { file: CORE + "types/skill.ts", has: "Optional roster blurb", c: "F" },
  { file: CORE + "types/skill.ts", has: "the workforce agent-level `contextMode`", c: "F" },
  { file: CORE + "types/skill.ts", has: "**Delegation tool seats — does gate.**", c: "F" },
  { file: CORE + "types/skill.ts", has: "`resolveToolSeats` seats exactly", c: "F" },
  { file: CORE + "types/skill.ts", has: "that declares none seats the whole", c: "F" },
  { file: CORE + "types/skill.ts", has: "It still never widens: seats are drawn", c: "F" },
  { file: CORE + "types/skill.ts", has: "`toolSeatFence`.", c: "KC" },
  { file: CORE + "types/skill.ts", has: "These are the board's *agent* seats", c: "F" },
  // engine
  { file: ENG + "execution/runAction.ts", has: "so a seat another board holds", c: "F" },
  { file: ENG + "execution/runAction.ts", has: "but the seat is held by", c: "F" },
  { file: ENG + "registry/flow-registry.ts", has: "The kind keeps its seat", c: "KE" },
  { file: ENG + "routes/route-utils.ts", has: "from an operator's seat", c: "KE" },
  { file: ENG + "stores/filesystem/trace-store.ts", has: "oster", c: "KE", n: 38 },
];
