/**
 * The render half of the code convention: discovered files become a module.
 *
 * What it emits is ordinary TypeScript with static imports, so every bundler
 * already knows what to do with it — which is the whole reason discovery is a
 * build step rather than something the framework does while the app runs.
 *
 * The file is committed, so it has to be diffable: the output is a pure
 * function of the discovered list, ordered by path, with nothing timestamped
 * and nothing keyed off a machine. A file that churns makes every PR noisy and
 * `--check` useless.
 *
 * Nothing here decides anything about registration. It renders three maps onto
 * the three parameters that already exist — the moment it merged built-ins or
 * reordered precedence it would be a second registration path.
 */

import { CODE_SLOTS, type CodeSlotId, type DiscoveredFile } from "./discover";

/** The generated module's name, under the workforce root. Public: an author imports it. */
export const GENERATED_FILE_NAME = "workforce.gen.ts";

/** Header on the emitted file, so nobody edits it by hand and everybody knows what re-makes it. */
const HEADER = `// Generated by \`fsdev gen\`. Do not edit.
//
// One entry per file under \`flows/workers/\`, \`flows/channels/\` and \`blocks/\`.
// Add or rename a file and re-run \`fsdev gen\`; \`fsdev gen --check\` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.`;

/**
 * How each map is typed in the emitted file.
 *
 * The types are what makes the app's own typecheck read every discovered file:
 * a file exporting the wrong shape fails to assign, naming the file. That check
 * is here rather than in the walk because the walk never opens a module.
 */
const SLOT_TYPES: Record<CodeSlotId, { imported: string; from: string; expression: string }> = {
  worker: {
    imported: "HireOptions",
    from: "@flow-state-dev/workforce",
    expression: 'NonNullable<HireOptions["kinds"]>',
  },
  channel: {
    imported: "ChannelInstancesOptions",
    from: "@flow-state-dev/workforce",
    expression: 'NonNullable<ChannelInstancesOptions["kinds"]>',
  },
  block: {
    imported: "BlockDefinition",
    from: "@flow-state-dev/core",
    expression: "Record<string, BlockDefinition>",
  },
};

/**
 * The local identifier one discovered file is imported under.
 *
 * Prefixed by slot because a worker kind and a block may legitimately share a
 * basename, and hyphens become camel humps because a basename is a path segment
 * and an identifier is not.
 */
function localName(file: DiscoveredFile): string {
  const camel = file.name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
  return `${file.slot}${camel}`;
}

/**
 * One map literal, keyed by name. Keys are quoted unconditionally, because a
 * hyphenated one must be and a rule with an exception is a rule that drifts.
 *
 * An empty map carries no `satisfies`, and so needs no type imported: there is
 * no member for a type to catch, and an app with no custom code of this kind
 * should not acquire an import because of a folder it does not have.
 */
function renderMap(files: DiscoveredFile[], exportName: string, expression: string): string {
  if (files.length === 0) return `export const ${exportName} = {};`;
  const entries = files.map((file) => `  ${JSON.stringify(file.name)}: ${localName(file)},`).join("\n");
  return `export const ${exportName} = {\n${entries}\n} satisfies ${expression};`;
}

/**
 * Render the module for a discovered tree.
 *
 * Deterministic: the same list renders the same bytes, on any machine, in any
 * directory order.
 *
 * @param files Every discovered file, as `discoverWorkforceCode` ordered them.
 * @returns The module's full text, newline-terminated.
 */
export function renderWorkforceCode(files: DiscoveredFile[]): string {
  const sections: string[] = [HEADER];

  // One type import per module a non-empty map's type comes from. An empty map
  // renders without `satisfies`, so it contributes nothing here.
  const typeImports = new Map<string, Set<string>>();
  for (const slot of CODE_SLOTS) {
    if (!files.some((file) => file.slot === slot.id)) continue;
    const { imported, from } = SLOT_TYPES[slot.id];
    const names = typeImports.get(from) ?? new Set<string>();
    names.add(imported);
    typeImports.set(from, names);
  }

  const importLines: string[] = [];
  for (const from of [...typeImports.keys()].sort()) {
    const names = [...(typeImports.get(from) ?? [])].sort().join(", ");
    importLines.push(`import type { ${names} } from ${JSON.stringify(from)};`);
  }
  // Ordered by path, which is the order `discoverWorkforceCode` returns.
  for (const file of files) {
    importLines.push(`import ${localName(file)} from ${JSON.stringify(file.importPath)};`);
  }
  if (importLines.length > 0) sections.push(importLines.join("\n"));

  for (const slot of CODE_SLOTS) {
    const mine = files.filter((file) => file.slot === slot.id);
    sections.push(renderMap(mine, slot.exportName, SLOT_TYPES[slot.id].expression));
  }

  return `${sections.join("\n\n")}\n`;
}
