/**
 * The render half of the code convention: discovered files become a module.
 *
 * What it emits is ordinary TypeScript with static imports, so every bundler
 * already knows what to do with it — which is the whole reason discovery is a
 * build step rather than something the framework does while the app runs.
 *
 * The file is committed, so it has to be diffable: the output is a pure
 * function of the discovered list, ordered by path, with nothing timestamped
 * and nothing keyed off a machine. A file that churns makes every PR noisy and
 * `--check` useless.
 *
 * Nothing here decides anything about registration. It renders four maps onto
 * parameters that already exist — three locked code folders, and the resource
 * modules an app splits into the `uses` and the resource map it already passes.
 * The moment it merged built-ins or reordered precedence it would be a second
 * registration path.
 */

import { CODE_SLOTS, type CodeSlotId, type DiscoveredFile } from "./discover";
import type { DiscoveredResourceModule } from "./discover-resource-modules";
import type { DiscoveredSeatBlock } from "./discover-seat-blocks";

/** The generated module's name, under the workforce root. Public: an author imports it. */
export const GENERATED_FILE_NAME = "workforce.gen.ts";

/** Header on the emitted file, so nobody edits it by hand and everybody knows what re-makes it. */
const HEADER = `// Generated by \`fsdev gen\`. Do not edit.
//
// One entry per file under \`flows/workers/\`, \`flows/channels/\` and \`blocks/\`,
// one per TypeScript file in a \`resources/\` folder, and one per seat per file
// in a team's or a worker's own \`blocks/\` folder.
// Add or rename a file and re-run \`fsdev gen\`; \`fsdev gen --check\` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.`;

/**
 * How each map is typed in the emitted file.
 *
 * The types are what makes the app's own typecheck read every discovered file:
 * a file exporting the wrong shape fails to assign, naming the file. That check
 * is here rather than in the walk because the walk never opens a module.
 */
const SLOT_TYPES: Record<CodeSlotId, { imported: string; from: string; expression: string }> = {
  worker: {
    imported: "HireOptions",
    from: "@flow-state-dev/workforce",
    expression: 'NonNullable<HireOptions["kinds"]>',
  },
  channel: {
    imported: "ChannelInstancesOptions",
    from: "@flow-state-dev/workforce",
    expression: 'NonNullable<ChannelInstancesOptions["kinds"]>',
  },
  block: {
    imported: "BlockDefinition",
    from: "@flow-state-dev/core",
    expression: "Record<string, BlockDefinition>",
  },
};

/** The map Door B's modules are rendered onto. Public: an app imports it beside `kinds`. */
const RESOURCE_MODULES_EXPORT = "resourceModules";

/**
 * How the module map and its worker-scoped entries are typed in the emitted
 * file.
 *
 * The map's own type is what makes a module exporting neither a capability nor
 * a resource fail to assign, naming its file. The per-entry one is the refusal
 * for a capability in a single worker's own folder: nothing in the walk can
 * tell a capability from a resource without opening the module, so the type is
 * where that check can happen at all.
 */
const RESOURCE_MODULE_TYPES = {
  from: "@flow-state-dev/workforce",
  map: "ResourceModules",
  atWorkerRoot: "WorkerResourceModuleExport",
} as const;

/**
 * The local identifier one discovered file is imported under.
 *
 * Prefixed by slot because a worker kind and a block may legitimately share a
 * basename, and hyphens become underscores because a basename is a path segment
 * and an identifier is not.
 *
 * Underscores rather than camel humps, because the mapping has to be
 * **injective** and capitalising is not: a basename is `[a-z0-9]+` joined by
 * single hyphens, so upper-casing the first character of each part is a no-op
 * on a digit and `a0` and `a-0` both came out as `a0`. Two distinct kinds then
 * shared one binding, and the module was emitted — reported as written — with a
 * duplicate import that no bundler could compile. `_` cannot appear in a
 * validated segment, so swapping it for `-` is reversible by construction and
 * no two basenames can meet.
 */
function localName(file: DiscoveredFile): string {
  return `${file.slot}_${file.name.replace(/-/g, "_")}`;
}

/**
 * One map literal, keyed by name. Keys are quoted unconditionally, because a
 * hyphenated one must be and a rule with an exception is a rule that drifts.
 *
 * An empty map carries no `satisfies`, and so needs no type imported: there is
 * no member for a type to catch, and an app with no custom code of this kind
 * should not acquire an import because of a folder it does not have.
 */
function renderMap(files: DiscoveredFile[], exportName: string, expression: string): string {
  if (files.length === 0) return `export const ${exportName} = {};`;
  const entries = files.map((file) => `  ${JSON.stringify(file.name)}: ${localName(file)},`).join("\n");
  return `export const ${exportName} = {\n${entries}\n} satisfies ${expression};`;
}

/**
 * The local identifier one discovered module is imported under.
 *
 * Injective, like {@link localName} and for the same reason: two modules
 * sharing a binding emits a module with a duplicate import that no bundler can
 * compile, reported as written. A ref is validated segments joined by `/`, and
 * a segment admits neither `_` nor a doubled `-`, so a run of underscores here
 * is one (from a hyphen) or two (from a slash) and never more — which makes the
 * mapping reversible by construction.
 */
function moduleLocalName(module: DiscoveredResourceModule): string {
  return `resource_${module.ref.replace(/-/g, "_").replace(/\//g, "__")}`;
}

/**
 * What the emitted file says about the narrower entries, once, above the map.
 *
 * The compiler cannot say it: it resolves the alias down to the union's own
 * name, so the error reads as a shape mismatch and not as a rule. This is the
 * sentence an author lands next to when their editor points at the line — so
 * the refusal names the file, the ref AND the reason. Emitted only when the
 * tree actually has a module at a worker root.
 */
const WORKER_ROOT_NOTE =
  `// A worker's own \`resources/\` folder holds resources, not capabilities:\n` +
  `// every seat of a kind shares that kind's capabilities, so one installed\n` +
  `// from a single worker's folder would change every other seat. Move a\n` +
  `// capability up to the team's or the organisation's \`resources/\` folder.`;

/**
 * The `resourceModules` map, keyed by ref.
 *
 * A module in a worker's own folder carries its own narrower `satisfies`, so
 * the compiler refuses a capability written at that root. The kind-wide entries
 * carry none: the map's own type covers them, and a second annotation per line
 * would be noise in a committed file.
 */
function renderModuleMap(modules: DiscoveredResourceModule[]): string {
  if (modules.length === 0) return `export const ${RESOURCE_MODULES_EXPORT} = {};`;
  const note = modules.some((module) => module.atWorkerRoot) ? `${WORKER_ROOT_NOTE}\n` : "";
  const entries = modules
    .map((module) => {
      const value = module.atWorkerRoot
        ? `${moduleLocalName(module)} satisfies ${RESOURCE_MODULE_TYPES.atWorkerRoot}`
        : moduleLocalName(module);
      return `  ${JSON.stringify(module.ref)}: ${value},`;
    })
    .join("\n");
  return (
    `${note}export const ${RESOURCE_MODULES_EXPORT} = {\n${entries}\n} ` +
    `satisfies ${RESOURCE_MODULE_TYPES.map};`
  );
}

/** The map Door C's registrations are rendered onto. Public: an app imports it beside `kinds`. */
const SEAT_BLOCKS_EXPORT = "seatBlocks";

/**
 * The local identifier one seat-block FILE is imported under — one binding per
 * file, however many seats register it.
 *
 * Injective, like {@link localName} and for its reason: two files sharing a
 * binding emits a module with a duplicate import that no bundler can compile.
 * Both forms are built from validated segments, which admit neither `_` nor a
 * doubled `-`, so a run of underscores here is one (from a hyphen) or two (from
 * a level join) and never more.
 */
function seatBlockLocalName(entry: DiscoveredSeatBlock): string {
  const safe = (segment: string): string => segment.replace(/-/g, "_");
  if (entry.level === "team") {
    // Keyed by the TEAM rather than by the seat: one file, one binding.
    const team = entry.path.split("/")[1] ?? "";
    return `teamblock_${safe(team)}__${safe(entry.name)}`;
  }
  return `seatblock_${safe(entry.seat.replace(".", "__"))}__${safe(entry.name)}`;
}

/**
 * The `seatBlocks` map: seat id → block name → block.
 *
 * Nested rather than flat because the seat is the scope — a block registered
 * for one seat is not registered for its neighbour, and a flat key would put
 * the isolation in a string-splitting rule instead of in the shape.
 */
function renderSeatBlockMap(entries: DiscoveredSeatBlock[]): string {
  if (entries.length === 0) return `export const ${SEAT_BLOCKS_EXPORT} = {};`;

  const bySeat = new Map<string, DiscoveredSeatBlock[]>();
  for (const entry of entries) {
    const held = bySeat.get(entry.seat) ?? [];
    held.push(entry);
    bySeat.set(entry.seat, held);
  }

  const seats = [...bySeat.keys()].sort();
  const body = seats
    .map((seat) => {
      const rows = [...bySeat.get(seat)!]
        .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
        .map((entry) => `    ${JSON.stringify(entry.name)}: ${seatBlockLocalName(entry)},`)
        .join("\n");
      return `  ${JSON.stringify(seat)}: {\n${rows}\n  },`;
    })
    .join("\n");

  return (
    `export const ${SEAT_BLOCKS_EXPORT} = {\n${body}\n} ` +
    `satisfies Record<string, Record<string, BlockDefinition>>;`
  );
}

/**
 * Every seat-block file, once, in the order the imports are emitted.
 *
 * A team-level file is registered for every seat on its team, so the entry list
 * carries it once per seat and the import list must not.
 */
function seatBlockImports(entries: DiscoveredSeatBlock[]): DiscoveredSeatBlock[] {
  const seen = new Set<string>();
  const unique: DiscoveredSeatBlock[] = [];
  for (const entry of entries) {
    if (seen.has(entry.path)) continue;
    seen.add(entry.path);
    unique.push(entry);
  }
  return unique;
}

/**
 * Render the module for a discovered tree.
 *
 * Deterministic: the same list renders the same bytes, on any machine, in any
 * directory order.
 *
 * @param files Every discovered code file, as `discoverWorkforceCode` ordered them.
 * @param modules Every discovered resource module, in the same order it returned them.
 * @param seatBlocks Every per-seat block registration, in the same order it returned them.
 * @returns The module's full text, newline-terminated.
 */
export function renderWorkforceCode(
  files: DiscoveredFile[],
  modules: DiscoveredResourceModule[],
  seatBlocks: DiscoveredSeatBlock[] = [],
): string {
  const sections: string[] = [HEADER];

  // One type import per module a non-empty map's type comes from. An empty map
  // renders without `satisfies`, so it contributes nothing here.
  const typeImports = new Map<string, Set<string>>();
  const needType = (from: string, imported: string): void => {
    const names = typeImports.get(from) ?? new Set<string>();
    names.add(imported);
    typeImports.set(from, names);
  };
  for (const slot of CODE_SLOTS) {
    if (!files.some((file) => file.slot === slot.id)) continue;
    const { imported, from } = SLOT_TYPES[slot.id];
    needType(from, imported);
  }
  // The seat map's own type. `BlockDefinition` may already be imported by the
  // locked `blocks` folder's map; `needType` dedupes.
  if (seatBlocks.length > 0) needType(SLOT_TYPES.block.from, SLOT_TYPES.block.imported);
  if (modules.length > 0) {
    needType(RESOURCE_MODULE_TYPES.from, RESOURCE_MODULE_TYPES.map);
    // Only when one is actually at a worker root: an app with none should not
    // acquire an import for a rule its tree never meets.
    if (modules.some((module) => module.atWorkerRoot)) {
      needType(RESOURCE_MODULE_TYPES.from, RESOURCE_MODULE_TYPES.atWorkerRoot);
    }
  }

  const importLines: string[] = [];
  for (const from of [...typeImports.keys()].sort()) {
    const names = [...(typeImports.get(from) ?? [])].sort().join(", ");
    importLines.push(`import type { ${names} } from ${JSON.stringify(from)};`);
  }
  // Ordered by path, which is the order `discoverWorkforceCode` returns.
  for (const file of files) {
    importLines.push(`import ${localName(file)} from ${JSON.stringify(file.importPath)};`);
  }
  for (const module of modules) {
    importLines.push(`import ${moduleLocalName(module)} from ${JSON.stringify(module.importPath)};`);
  }
  for (const entry of seatBlockImports(seatBlocks)) {
    importLines.push(
      `import ${seatBlockLocalName(entry)} from ${JSON.stringify(entry.importPath)};`,
    );
  }
  if (importLines.length > 0) sections.push(importLines.join("\n"));

  for (const slot of CODE_SLOTS) {
    const mine = files.filter((file) => file.slot === slot.id);
    sections.push(renderMap(mine, slot.exportName, SLOT_TYPES[slot.id].expression));
  }
  sections.push(renderModuleMap(modules));
  sections.push(renderSeatBlockMap(seatBlocks));

  return `${sections.join("\n\n")}\n`;
}
