// Generated by `fsdev gen`. Do not edit.
//
// One entry per file under `flows/workers/`, `flows/channels/` and `blocks/`,
// one per TypeScript file in a `resources/` folder, one per seat per file in
// a team's or a worker's own `blocks/` folder, and one per file in a
// package's `blocks/` folder.
// Add or rename a file and re-run `fsdev gen`; `fsdev gen --check` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.

import type { ResourceModules } from "@flow-state-dev/workforce";
import resource_teams__support__research from "./teams/support/resources/research";

export const kinds = {};

export const channelKinds = {};

export const blocks = {};

export const resourceModules = {
  "teams/support/research": resource_teams__support__research,
} satisfies ResourceModules;

export const seatBlocks = {};

export const packageBlocks = {};
