// Generated by `fsdev gen`. Do not edit.
//
// One entry per file under `flows/workers/`, `flows/mailboxes/` and `blocks/`,
// one per TypeScript file in a `resources/` folder, one per seat per file in
// a team's or a worker's own `blocks/` folder, and one per file in a
// package's `blocks/` folder.
// Add or rename a file and re-run `fsdev gen`; `fsdev gen --check` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.

export const kinds = {};

export const mailboxKinds = {};

export const blocks = {};

export const resourceModules = {};

export const seatBlocks = {};

export const packageBlocks = {};
