// Generated by `fsdev gen`. Do not edit.
//
// One entry per file under `flows/workers/`, `flows/channels/` and `blocks/`,
// and one per TypeScript file in a `resources/` folder.
// Add or rename a file and re-run `fsdev gen`; `fsdev gen --check` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.

import type { BlockDefinition } from "@flow-state-dev/core";
import type { HireOptions } from "@flow-state-dev/workforce";
import block_desk_note from "./blocks/desk-note";
import worker_desk_clerk from "./flows/workers/desk-clerk";

export const kinds = {
  "desk-clerk": worker_desk_clerk,
} satisfies NonNullable<HireOptions["kinds"]>;

export const channelKinds = {};

export const blocks = {
  "desk-note": block_desk_note,
} satisfies Record<string, BlockDefinition>;

export const resourceModules = {};
