// Generated by `fsdev gen`. Do not edit.
//
// One entry per file under `flows/workers/`, `flows/channels/` and `blocks/`.
// Add or rename a file and re-run `fsdev gen`; `fsdev gen --check` fails when
// this file and the tree disagree. Committed on purpose — a fresh clone has to
// typecheck before anything has been generated.

import type { BlockDefinition } from "@flow-state-dev/core";
import type { HireOptions } from "@flow-state-dev/workforce";
import blockDeskNote from "./blocks/desk-note";
import workerDeskClerk from "./flows/workers/desk-clerk";

export const kinds = {
  "desk-clerk": workerDeskClerk,
} satisfies NonNullable<HireOptions["kinds"]>;

export const channelKinds = {};

export const blocks = {
  "desk-note": blockDeskNote,
} satisfies Record<string, BlockDefinition>;
